---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: apps
spec:
  provider:
    gcpsm:
      projectID: dito-production
      auth:
        workloadIdentity:
          clusterLocation: southamerica-east1
          clusterName: dito-production-gke
          serviceAccountRef:
            name: dito-api
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dito-api-secrets
  namespace: apps
spec:
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: dito-production-db-password
    - secretKey: APP_API_KEY
      remoteRef:
        key: dito-production-app-api-key
