apiVersion: v1
kind: ConfigMap
metadata:
  name: dito-api-config
  namespace: apps
data:
  APP_ENV: "production"
  LOG_LEVEL: "info"
  CLOUD_SQL_CONNECTION_NAME: "dito-production:southamerica-east1:dito-production-pg"
