apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Overlay de DEVELOPER (projeto Teste-dito, cluster zonal).

resources:
- ../../base

images:
- name: dito-internal-api
  newName: southamerica-east1-docker.pkg.dev/project-4a372108-be7a-4159-966/dito-developer-docker/dito-internal-api
  newTag: 872a9ce

replicas:
- count: 2
  name: dito-api

patches:
- path: patch-configmap.yaml
- path: patch-httproute.yaml
- path: patch-serviceaccount.yaml
- path: patch-externalsecret.yaml
