apiVersion: v1
kind: ServiceAccount
metadata:
  name: dito-api
  namespace: apps
  annotations:
    iam.gke.io/gcp-service-account: dito-developer-app@project-4a372108-be7a-4159-966.iam.gserviceaccount.com
